services:
  alert-svc:
    build:
      context: alert_svc
    container_name: alert_svc
    restart: unless-stopped
    init: true
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DEBUG=false
    networks:
      - caz-net
    depends_on:
      - detection-svc
      - intel-svc

  detection-svc:
    build:
      context: detection_svc
    container_name: detection_svc
    restart: unless-stopped
    init: true
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=caz_db
      - DB_USER=caz_user
      - DB_PASSWORD=caz_pass
    networks:
      - caz-net
    depends_on:
      - postgres

  intel-svc:
    build:
      context: intel_svc
    container_name: intel_svc
    restart: unless-stopped
    init: true
    ports:
      - "5008:5008"
    environment:
      - PORT=5008
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=caz_db
      - DB_USER=caz_user
      - DB_PASSWORD=caz_pass
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    networks:
      - caz-net
    depends_on:
      - postgres
      - tempo

  postgres:
    image: postgres:16
    container_name: caz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: caz_db
      POSTGRES_USER: caz_user
      POSTGRES_PASSWORD: caz_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - caz-net

  tempo:
    image: grafana/tempo:1.21.0
    container_name: tempo
    restart: unless-stopped
    ports:
      - "4318:4318"
    networks:
      - caz-net

networks:
  caz-net:
    driver: bridge

volumes:
  postgres_data: