version: "3.9"

services:
  alert-svc:
    build:
      context: ./alert-svc
    container_name: alert-svc
    restart: unless-stopped
    init: true
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    networks:
      - caz-net

  detection-svc:
    build:
      context: ./detection-svc
    container_name: detection-svc
    restart: unless-stopped
    init: true
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - caz-net

networks:
  caz-net:
    driver: bridge