version: "3.9"

services:
  alert-svc:
    build:
      context: alert_svc
    container_name: alert_svc
    restart: unless-stopped
    init: true
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    networks:
      - caz-net

  detection-svc:
    build:
      context: detection_svc
    container_name: detection_svc
    restart: unless-stopped
    init: true
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
    networks:
      - caz-net

  intel-svc:
    build:
      context: intel_svc
    container_name: intel_svc
    restart: unless-stopped
    init: true
    ports:
      - "5008:5008"
    environment:
      - PORT=5008
    networks:
      - caz-net

networks:
  caz-net:
    driver: bridge