name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
#
#      - name: Build and Push Dockerfiles
#        env:
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#        run: |
#          find . -name "Dockerfile" | while read dockerfile; do
#            dir=$(dirname "$dockerfile")
#            service_name=$(basename "$dir")
#
#            echo "📦 Building $service_name from $dockerfile"
#
#            IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service_name:${GITHUB_SHA}"
#            docker build -t $IMAGE "$dir"
#            docker tag $IMAGE "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service_name:latest"
#
#            echo "🚀 Pushing $service_name to ECR..."
#            docker push $IMAGE
#            docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service_name:latest"
#          done