name: Create Prod Release

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: Service
        required: true
        type: string
      uat_tag:
        description: UAT Tag to Promote
        required: true
        type: string

jobs:
  promote-to-prod:
    name: Promote ${{ inputs.service_name }} to Production
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: ${{ inputs.service_name }}
      VERSION: ${{ inputs.uat_tag }}
      UAT_TAG: uat_${{ inputs.uat_tag }}
      PROD_TAG: prod_${{ inputs.uat_tag }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Promote $SERVICE_NAME:$UAT_TAG → $PROD_TAG
        run: |
          docker pull "$ECR_URI/$SERVICE_NAME:$UAT_TAG"
          docker tag "$ECR_URI/$SERVICE_NAME:$UAT_TAG" "$ECR_URI/$SERVICE_NAME:$PROD_TAG"
          docker push "$ECR_URI/$SERVICE_NAME:$PROD_TAG"
          echo "Promoted $SERVICE_NAME:$UAT_TAG → $PROD_TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PROD_TAG }}
          name: Production Release - ${{ env.SERVICE_NAME }} ${{ env.VERSION }}
          body: |
            Promoted `${{ env.SERVICE_NAME }}` from `uat_${{ env.VERSION }}` to `prod_${{ env.VERSION }}`.
            
            Image URI: `${{ env.ECR_URI }}/${{ env.SERVICE_NAME }}:${{ env.PROD_TAG }}`
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}