name: Trigger Dev Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  call-build-push-images:
    uses: build-images.yaml
    with:
      environment: dev
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      REPO_PAT: ${{ secrets.REPO_PAT }}